### ISSUE TITLE
Pruning takes to much

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#18] opened 2019-12-22 18:30 UTC
[configs.zip](https://github.com/lurkbbs/e621dl/files/3992839/configs.zip)

don't know why but whenever it have it set to prune my cache and donwloads it wipes out everyting and i don't know why

Haven't tested it much but pruning doesn't seem to work all that much.

**Comment by lurkbbs** [comment] 2019-12-22 19:01
I'm on it

**Comment by huskelord** [comment] 2019-12-22 20:09
i figured it out i think. i'm testing it now but i belive it got rid of everyting except whatever was posted over the last 10 days because i limited days value to 10 to save time. running it now to see if it works right after changing the days value back to 999999

**Comment by lurkbbs** [comment] 2019-12-22 20:15
IDK, everything works fine and just as it specified.
Just now, I downloaded e621dl.exe, all configs, first run it to get images, then I changed second config to prune everything and ran it again.

First, only last 10 days are actually requested and loaded to database. Second, third config is with disabled cache, so it maybe not pruning but just not filling cache. 

Now, let's take a look. Suppose we downloaded....

Doesn't matter, you're figured it out 😄

**Comment by lurkbbs** [comment] 2019-12-22 20:24
By the way, if you want to update database only for the last few days, you can make a copy of relevant config, change it to db and set max_days_ago to a big number. 999999 is about 2700 years back, should be good enough. But, I sometimes get tag update for posts of 7 years or more, so I prefer to get it all anyway.
Next thing, I recommend to get all api only in the first config, since you most permissive prefilter is the same across configs and getting everything from api second time is somewhat meaningless and rather slow

**Comment by huskelord** [comment] 2019-12-23 04:14
The reason I have artists on their own is because i want download pools to only be for artists and not anyting else when you get around to it. I guess I can just add it to a separate db config now that I think about it
Edit1: I actually cant because the first api is s q and e posts while the second is only e

**Comment by huskelord** [comment] 2019-12-23 04:37
Just curious but is there a way that I could get posts that I'll bypass the default blacklisting because I'm sure there will be a few in some comics that i will want once the pool gets done

**Comment by huskelord** [comment] 2019-12-23 08:06
im having trouble with my currrent config settup it keep skiping the first config even though i know that there are some post that need to be downloaded/copied that aren't

[configs.zip](https://github.com/lurkbbs/e621dl/files/3994518/configs.zip)

edit1: I think i fixed it by changing the config names from config1 to 1 config
edit2: nvm I'm running to a bunch of other problems too.  i updated the config.zip to what i curenlty have but im going to run on no_close and try to figure this out.
Edit3: it was the date again. but i think i noticed a problem related to that the program will run only as long as the shortes or first date value nomater what config it is on, If the first/shortest date value is 15 all configs will only run the date value at 15 (I could be wrong but it doesn't change the fact that the configs wouldn't run to completion

**Comment by lurkbbs** [comment] 2019-12-23 15:57
> If the first/shortest date value is 15 all configs will only run the date value at 15

If you deleted `posts.db` then in new database there is no posts beyond 30 days therefore all posts from db ends earlier then expected.
Check `posts.db` size. If it's more than 1 GB, it is really a bug. If it's smaller, most likely less than 100 Mb, than it's not a bug and you need to get all posts from api at least once.

>Just curious but is there a way that I could get posts that I'll bypass the default blacklisting because I'm sure there will be a few in some comics that i will want once the pool gets done

Not for now. By the time pools are actually relevant global blacklist mechanics as well as all the settings will be changed anyway

**Comment by huskelord** [comment] 2019-12-27 03:05
Merry christamas (its the day after but so what.) ive been away for the holidays and didn't get a chance to get back with you until now. 

for the bug above i forgot the check the file itself but when i downloaded with the date value at 10 until completion only a few files survived the pruning but when i changed it back everyting was fine. 

After i did a mass self blacklisting and reran the program to completion i noticed that the to_blacklist_post folder was empty like its supposed to be but the the post were back in the folders i grabed them from to blacklist them. the blacklist document also didn't have the post names in it.

here are the configs i got
[configs.zip](https://github.com/lurkbbs/e621dl/files/4004004/configs.zip)

**Comment by lurkbbs** [comment] 2019-12-27 20:14
Merry Christmas!
By the way, we, Russians, we still use Julian calendar in our Orthodox church, so it's about 13 day before. But who cares, that means we have two Christmas symmetrically before and after New Year! So merry import Christmas, wait for export Christmas on 7 of January 😄 

For the bugs, I'll look into it tomorrow. As I understand it, posts from "blacklist.txt" are there in the folders despite being in the blacklist. Not good, I'll make it disappear tomorrow or in the Sunday.

From 30 of December to 3 of January I'll be unavailable, because we Atheistic Russians celebrate New Year as a great holiday, not Christmas, which is a nice bonus. And by celebrate I mean be drunk (one day) and relax (another day) and play games I wanted to play a looong time ago (another day).

Well, not many are actually atheist these days, but New Year is really about the same thing as Christmas in at least USA, Canada and Western Europe, but most likely everywhere else. Eight days of no work (1-8 January) included. And that means I'll finally be able to _improve_ e621dl, not just minor patches and bugfixes here and there.

**Comment by huskelord** [comment] 2019-12-27 20:21
Sounds great hope to hear from you soon.

**Comment by lurkbbs** [comment] 2019-12-28 10:54
I couldn't reproduce the bug.

Changes from configs:
* Disabled cache pruning
* Added `make_cache = true` to the second config
* `offline = true` in all configs

My steps:

1. Run configs.
2. Copy `specifed for blacklisting` folder to `to_blocked_posts`
3. Run configs. At that point `specifed for blacklisting` was removed from downloads
4. Run configs again. Blacklisted posts was not copied.

I tried to add random files to downloads folder, as well as `to_blocked_posts` folder. Everything was fine.

There is one thing that could cause blacklist.txt to be cleared. If the app was terminated in exactly wrong moment when the file was updated, then it could be cleared but not updated.

If your problem is still there, after you copied/moved files to `to_blocked_posts`, run powershell from the folder and execute:
`tree /F /A > "files.txt"`
from there and upload files.txt here. Inside should be filenames and folder structure.

**Comment by huskelord** [comment] 2020-01-03 04:32
sorry for the late reply everyting seems to be working when it comes to the blacklisting it must have been my timing closeing the config.

**Comment by lurkbbs** [comment] 2020-01-03 17:31
Still not sure what happened there, but alright.

I as said, I want to change a lot, and I want to start with configuration format. Classic *.ini files are bad at hierarchical structures. So, I chose YAML, it will look like that:

```yaml
global settings:
    # include_md5 : false -- to hell with that
    # make_hardlinks : true -- always.
    #                  more than that, app should check if
    #                  it's possible, and if not, try
    #                  symlinks, and only then copies
    # make_cache : true -- also always true. We use
    #                      hardlinks! Or symlinks,
    #                      doesn't matter much. Copies
    #                      only if there is no possible way
    #                      to make either of the above
    # db : true  -- this is true too. Too much of
    #               advanced case scenarios just won't work
    #               and frankly, I'm tired of all the flags
    #               and how they should work with each other
    prune downloads : false
    prune cache : false
    offline : true
    # I plan to add a folder where
    # every new images are hardlinked
    # folder structure is similar
    # with downloads
    # should be cleared on every new run
    recent updates folder: new

anchors:
    gender interactions: &gi 
        - solo
        - another_tag
        - yet_another_tag
    everything and misc: &em
        misc subfolder : .Overflow
        everything subfolder: ...Everything
    blacklist: &bl
        - bad_tag
        - another_bad_tag

section settings templates:
    defaults:
        #days should not be 
        days : 999999
        ratings : s q e
        min score : 0
        min favs : 0
        # posts_from should not be on per folder basis
        # it's only valid for queries
        
        blacklist:
            - *bl
        
        everything subfolder: false
        misc subfolder : false
        
        subfolders :
            - ..images:
                << : *em
                tags:
                    - -animated
                subfolders:
                    - *gi
                
            
            - ..Animated:
                tags: animated
                subfolders: 
                    - sound:
                        << : *em
                        tags:
                            - sound
                        subfolders:
                            - *gi
                    - No_Sound:
                        << : *em
                        tag: 
                            - -sound
                        subfolders:
                            - *gi
            

    no subfolders:
        base: defaults
        subfolders : 

folders:
    species:
        subfolders:
            - Animal Base:
                subfolders:
                    - arthropod:
                        subfolders:
                            - hymenopteran:
                                tags:
                                    - hymenopteran
                                subfolders:
                                    - wasp
                                    - hornet
                                    - bee
                                    - ant
                                misc subfolder : .hymenopteran_-specified
                            - lepidopteran:
                                tags:
                                    - lepidopteran
                                subfolders:
                                    - butterfly
                                    - moth
                                misc subfolder : .lepidopteran_-specified
                            - arachnid
                            - myriapod:
                                tags:
                                    - myriapod
                                subfolders:
                                    - millipede
                                    - centipede
                                misc subfolder : .myriapod_-specified
                            - mantis
                    - Rodent:
                        subfolders:
                            - murid:
                                tags:
                                    - murid
                                subfolders:
                                    - mouse
                                    - rat
                                misc subfolder : .myriapod_-specified

queries:
    Everything_images:
        # Note: no additional time constraint
        query: -animated
        query source: remote # "local" for local database
        # Queries have all the properties of folders
        # but everything related with subfolders
        # and actual downloading of files is
        # ignored if this option is in use:
        used folders:
            - species
            
    Everything_animated:
        query:  animated
        query source: remote 
        used folders:
            - species
```

YAML do not requires quotes everywhere and generally easy to than TOML. Unlike ini-files, yaml supports hierarchical structures rather easy. Also, it has build-in support for [anchors, aliases and merges](http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html), similar to my hack with [*subfolders], but since it supports hierarchy, they should be less frequent.

There are two downsides:
    1. It is a bit more complex than classic ini file.
    2. It's hard to work with YAML in classic Notepad, especially when it gets bigger. I work with [Notepad++](https://notepad-plus-plus.org/), there is [Notepad2](http://www.flos-freeware.ch/notepad2.htm) and some more.

I'll give you test yaml config for all your three configs, in one file. Check it out:
[test.zip](https://github.com/lurkbbs/e621dl/files/4020101/test.zip)

**Comment by lurkbbs** [comment] 2020-01-03 17:48
Also yes, I choose to always make a database, always use hardlinks whenever possible, and always make cache since, again, with hardlinks no duplicates took space.
Also, if folder contains no tags nor subfolders, by default tag is the name of the folder. I noticed it is our common pattern, especially regarding artists.

**Comment by huskelord** [comment] 2020-01-03 20:30
got it. this sounds like a great improvement will it be able to work right away or will it need to waight for an update to the program also what does the offline = True do exaclty never really figrued that out.

why is there a second blacklist in secion template

Is # the new ; where it will ignore everying behind it on that line

I noticed that the elf and taur didn't have the misc subfolder: .>respetive species<_-specifed is this because i had some

is there a blacklist_default_subfolders = true command that i can add or is there a way to get that to happen 
reason im asking is that there a some subfolders that don't have enough posts to have the gender filtration be viable thus I add the blacklist_default_subfolders = true command to keep all the posts in the main file and not have any subfolders
the fourth config shows this the most

here is my most up to date config setup
[configs.zip](https://github.com/lurkbbs/e621dl/files/4020881/configs.zip)
also if you can't tell the fourth config is for all the specifed for blacklisting that i have went through completly and don't want everyting added to it just the most recent

is it possible to make multiple sections and if not is there a way to specify certain serch queries have difrent day values

**Comment by lurkbbs** [comment] 2020-01-03 22:59
I'm not sure I understand all correctly, so quick answers.

* This just an example. Exactly nothing is done to make it work. I just need to be sure that you can edit this new format as easy as old. Feature requests are welcome.

* `offline = true` is mostly for debug. Everything related network is skipped. That is:
    - skips any tag check. I need to make sure no tag is tag alias, or else it won't work on some folders.
    - source is forced to db for everything.
    - files that are not in cache/downloads won't be downloaded

    Compare with regular posts_from: db, where files are downloaded and tags are checked.
* yes, '#' is YAML comments mark.
* there is no misc because it was commented in my version of config2.ini. Also, to show how it can be done in the new format.
* there is a more general version of `blacklist_default_subfolders = true`. In "section settings templates:", "defaults:" is what was "[default]" in ini files. Most notably, it appends "subfolders" to every sections where there are "tag", "days", "ratings", "min score", "min favs" and/or "blacklist" option.
   In new config format, this can be changed with "base" option, e.g "base: no subfolders" which you could noticed already there.

* I'm not sure what means "is it possible to make multiple sections". It is possible to have multiple bases. It is possible to have multiple folders. It is possible to make multiple diffirently named section to lead to the same folder with e.g. "folder name: general". It is definitely possible to make multiple queries. It is possible to reuse some of the setting with  [anchors, aliases and merges,](http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html), I even used it with ` gender interactions: &gi ` and
`subfolders:`
`    - *gi`
and with `everything and misc: &em` and `<< : *em`. Multiple configs was not planned. For YAML, there is a way to include content from another files ("as if copypasting"), it looks like this: `section name: !include filename.yml`. But no, I don't want to process multiple configs unless there is no other options or those options are way too hard for e621dl user.

* I actually never thought of different time fore queries. I can change default behavior for queries to override default days instead of using maximum of all folders. Every other options, including tags, ratings, favs and scores would work as additional filters, but no file will be downloaded to folder with query name nor to any folder in subfolders if there is `used folders: ` in the query. No, better yet, e621dl will be terminated with an error if there is `used folders: ` and `subfolders` in one query section. Same for `folder name:` and `subfolders`.

Side note: Days in prefilters (real actual queries) are hacked as hell. They are not what it written there but max value from all the sections except the prefilters. Inside e621dl days are transformed to additional metatag `date:YYYY-MM-DD`, which I don't want to do, because in some cases more filtering tag are good. Even there, three additional query tags (those in the blacklist, preferably the most popular to maximally reduce e621 polling) should be good. Actually, the only time date is needed is with `order:<smth>` metatags.

It will take a long time to make it all. I bet your configs will change by that time. In the meantime, I ask to to change it by yourself, get an experience. Maybe there will be some trouble with changing it by yourself.

you can check validity in https://yaml-online-parser.appspot.com/. If something is wrong, it will tell you line number where it all gone wrong. Also, I'll make a script that will generate folders from a config somewhere around monday. The code will be used in the e621dl anyway, so it's by no means a distraction.

**Comment by huskelord** [comment] 2020-01-04 05:13
All in all i think changeing to YAML is the correct choice to go and though it might take a while and answering some obvious questions i should be able to firgure it out (i am noob when it comes to anything codeing) 

I pretty figured out everyting i need to figure out for it to work on config for me so ill probably won't be making any changes major to the configs until the next major change if that be pool downloading or the complete change to yaml

for the diffrent sections that were behind ; like the elf and taur i had it like that to keep them from running to help with saving space while i went through major blacklisting to help free up space since i probably wont be able to get a good external hard drive anytime soon (im living the steriotical broke american college student life) im mentioning this just in case you were curious

ill read up on the links you gave me to try and learn things and clarify some questions ill no dought end up having.

if i understand you last bullet point you're going to try and add the default values like days, rating, and min/max to the queries because if so that is awesome and will definity give me and others more freedom to work with and get rid of my orignal need for multiple configs

Edit1: would it be possible to make a way for certain posts to bypass the blacklist since certain comic have pages that have tags that i have blacklisted but i would like to have the full comic downloaded.

**Comment by lurkbbs** [comment] 2020-01-04 11:49
> ill probably won't be making any changes major to the configs until the next major change

This could take awhile, really. Maybe another month or so. Also, I plan to make it new soft in a new repo, since it doesn't backward compatible with e621dl at all. Name it "glutapump" or something.

> if i understand you last bullet point you're going to try and add the default values like days, rating, and min/max to the queries

Yes. I didn't plan it, but I do now.

> would it be possible to make a way for certain posts to bypass the blacklist

I didn't plan it, but I do now. Let's go with a simple way. `Blacklists` is a property of defaults. If you:
* Make a base with no blacklist
* Make a query with some metatags like `pool:<pool_id>` and use the base.
* Make sure that post source is remote (aka api), than it should be possible.

Hm. Two thoughts:
* You most certainly can do it now. New config, no prefilters, no blacklists, `posts_from = api`, `pool:<pool_id>` as the first tag in `tags`. Multiple sections are fine.
* I should really do something to to keep pool belonging in a database in "glutapump".

**Comment by huskelord** [comment] 2020-01-04 12:17
I'm not worried about the blacklisted posts yet since the posts aren't sorted into indivdual comic folders yet

Is pool:>pool id< diffrent than the e621.net pool?

Also what is glutapump?

**Comment by lurkbbs** [comment] 2020-01-04 12:24
"glutapump" is a name for that new e621dl version with yaml config and a major internal rewrite.

No, it's a way to select only images from a pool.

E.g. to download "Paper trail", look and it url,  https://e621.net/pool/show/16238 , find it's id, 16238,
then use `pool:16238` to download it.

It won't download all the pools related with all the pictures, only manually selected few. Better than nothing anyway

Edit: And `ignore blacklist` is something hard to formalize. I can make a whitelist to ignore tags specifically in blacklist option in section/base/defaults, but for regular tags it's a bit hard to distinguish where blacklists starts and where particular folder negatives tags ends. One of those nearly unformalizable problem like "find a cat on a picture" or "salt to taste".

**Comment by huskelord** [comment] 2020-01-04 13:00
I may have come up with something that may work to download the pools not code but a mental pathway if you will. 

If a image is in a pool the pool id is added to a separate document like the blacklist document. 
It will then download any pools in that document renaming the file the pool images will be in to the name of the pool. 
If an image is a pool it will not show up in any folders instead a shortcut to the specific pool will be added to that folder. 

It might not sound or be as good as the original idea but it seems like it would be less of a hassle to do/figure out. 

Edit1: again i dont know coding that well or at all in some cases so I dont know if something like this would be even viable. 

Also what does glutapump mean or is just a random word you come up with.

**Comment by lurkbbs** [comment] 2020-01-04 17:34
> a mental pathway if you will.

Smart word would be "algorithm" :-D

Algorithm itself, sorry, I just can't make out what you mean.
The part I got is shortcut to pools inside main folder (great idea, btw, thanks) and to download (and update) all pools that have pictures that any of downloads folders. Or maybe only those that are in the list of pools that are generated from some subfolders, like with the blacklist.

Whatever it is, it will not be soon. At least for now you can download pools manually.

> what does glutapump mean

"monosodium glutamate pump". Monosodium glutamate E number is 621. Pump is pump 😄

**Comment by lurkbbs** [comment] 2020-06-08 19:50
OK, since I didn't write a single meaningful line on this thing, I think I should close it. Sorry it took me so long to realize that.

**Closed as completed by lurkbbs** 2020-06-08 19:50 UTC
